/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisis.gui.mod1;

import analisis.gui.MainMenu;
import analisis.math.Algoritmos;
import analisis.math.InvalidInput;
import analisis.math.VM;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franco
 */
public class Modulo1 extends javax.swing.JFrame {
    
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static String funcion;
     

    /**
     * Creates new form NewJFrame
     */
    public Modulo1() {
        
        if(Algoritmos.abierto==false){
            modelo.addColumn("N");
        modelo.addColumn("P0");
        modelo.addColumn("P1");
        modelo.addColumn("Error");
        }
        Algoritmos.abierto=true;
        
        
        
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_funcionNewton = new javax.swing.JTextField();
        txt_toleranciaNewton = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_EjectuarNewton = new javax.swing.JButton();
        txt_iteracionesNewton = new javax.swing.JTextField();
        txt_raizNewton = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_newton = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_advertencia = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Graphics = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_iterations = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jreturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(990, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_funcionNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_funcionNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(txt_funcionNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 102, 140, -1));
        getContentPane().add(txt_toleranciaNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("Funcion f(x):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 106, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Tolerancia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btn_EjectuarNewton.setBackground(new java.awt.Color(255, 0, 51));
        btn_EjectuarNewton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_EjectuarNewton.setText("Ejecutar");
        btn_EjectuarNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EjectuarNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_EjectuarNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));
        getContentPane().add(txt_iteracionesNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 85, -1));
        getContentPane().add(txt_raizNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 108, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("# Iteraciones:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Raiz encontrada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        table_newton.setModel(modelo);
        jScrollPane1.setViewportView(table_newton);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 650, 310));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 255));
        jLabel5.setText("METODO DE NEWTON RAPHSON");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 13, -1, -1));

        lbl_advertencia.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lbl_advertencia.setText("Funcionando a la Perfeccion");
        getContentPane().add(lbl_advertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        lbl_estado.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lbl_estado.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lbl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Tolerancia por defecto 10^-6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Advertencias:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Resultados:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Tabla de datos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setText("Estado:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        btn_Graphics.setBackground(new java.awt.Color(255, 0, 51));
        btn_Graphics.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_Graphics.setText("Mostrar Grafica");
        btn_Graphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GraphicsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Graphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, -1));
        getContentPane().add(txt_iterations, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setText("Iteraciones:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jreturn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jreturn.setText("Volver");
        jreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreturnActionPerformed(evt);
            }
        });
        getContentPane().add(jreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_funcionNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_funcionNewtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_funcionNewtonActionPerformed

    private void btn_EjectuarNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EjectuarNewtonActionPerformed
//*****INICIALIZANDO VARIBALES***********************************************    
        String valor;
        Double tolerancia;
        Boolean vida = true;
        int iterations=0;
        
//*****BORRANDO DATOS DE LA TABLA SI ES QUE EXISTEN*************************************************        
        int rowCount = modelo.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
//*****************************************************************************************


//*****************************************************************************************    
        while(vida != false){
        if(txt_funcionNewton.getText().equals("")){
            lbl_advertencia.setText("Por favor ingrese una funcion");
            break;   
        }
        
        if(txt_toleranciaNewton.getText().equals("")){
            tolerancia = 0.000001;
            
        } else {
			tolerancia=0.0;
			try {
				tolerancia = VM.eval(txt_toleranciaNewton.getText(),0);
			} catch (InvalidInput ex) {
				Logger.getLogger(Modulo1.class.getName()).log(Level.SEVERE, null, ex);
			}
        }
        
        
        if(tolerancia<=0){   
            lbl_advertencia.setText("Ingrese una tolerancia valida");
            break;
        }
        
        if(txt_iterations.getText().equals("")){
            lbl_advertencia.setText("Ingrese el numero de iteraciones");
            break;
        }else{
            iterations = Integer.parseInt(txt_iterations.getText());
        }
        
        
        
        funcion =txt_funcionNewton.getText().toLowerCase();
        
        
        
        try{
            valor =Algoritmos.MetodoDeNewton(funcion,tolerancia,iterations);
            
            
        
        if( Algoritmos.newton == false){
            lbl_estado.setText("EL METODO FALLO");
            txt_raizNewton.setText(valor);
            txt_iteracionesNewton.setText(""+Algoritmos.iteraciones);
        }else{
            lbl_estado.setText("EL METODO TUVO EXITO");
            txt_raizNewton.setText(valor);
            txt_iteracionesNewton.setText(""+Algoritmos.iteraciones);
        }
        
        vida=false;
        }   catch (InvalidInput ex) {
                Logger.getLogger(Modulo1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
       
    }//GEN-LAST:event_btn_EjectuarNewtonActionPerformed

    private void btn_GraphicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GraphicsActionPerformed
        // TODO add your handling code here:
        Boolean vida = true;
        while(vida != false){
        if(txt_funcionNewton.getText().equals("")){
            lbl_advertencia.setText("Por favor ingrese una funcion para mostrar su grafica");
            break;   
            }else{
            break;
        }
        }
        
        NewtonGraphics graficaNewton = null;
        try {
            graficaNewton = new NewtonGraphics();
        } catch (InvalidInput ex) {
            Logger.getLogger(Modulo1.class.getName()).log(Level.SEVERE, null, ex);
        }
        graficaNewton.setVisible(true);
        
    }//GEN-LAST:event_btn_GraphicsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //PdfWriter.getInstance(document, new FileOutputStream(seleccionar.getSelectedFile() + ".pdf"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreturnActionPerformed
        // TODO add your handling code here:
        MainMenu menu=new MainMenu();menu.setVisible(true);this.setVisible(false);
    }//GEN-LAST:event_jreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EjectuarNewton;
    private javax.swing.JButton btn_Graphics;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jreturn;
    private javax.swing.JLabel lbl_advertencia;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JTable table_newton;
    private javax.swing.JTextField txt_funcionNewton;
    private javax.swing.JTextField txt_iteracionesNewton;
    private javax.swing.JTextField txt_iterations;
    private javax.swing.JTextField txt_raizNewton;
    private javax.swing.JTextField txt_toleranciaNewton;
    // End of variables declaration//GEN-END:variables
}
